FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:edge

RUN echo "deb [arch=amd64] http://deb.debian.org/debian bookworm main" > /etc/apt/sources.list.d/debian.list && \
    echo "deb [arch=amd64] http://deb.debian.org/debian bookworm-updates main" >> /etc/apt/sources.list.d/debian.list

RUN apt-get update && apt-get install -y \
    libwebkit2gtk-4.1-dev \
    libgtk-3-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev \
    && rm -rf /var/lib/apt/lists/*
