FROM ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:edge

RUN dpkg --add-architecture armhf

RUN echo "deb [arch=amd64,armhf] http://deb.debian.org/debian bookworm main" > /etc/apt/sources.list.d/debian.list && \
    echo "deb [arch=amd64,armhf] http://deb.debian.org/debian bookworm-updates main" >> /etc/apt/sources.list.d/debian.list

RUN apt-get update && apt-get install -y \
    libwebkit2gtk-4.1-dev:armhf \
    libgtk-3-dev:armhf \
    libayatana-appindicator3-dev:armhf \
    librsvg2-dev:armhf \
    && rm -rf /var/lib/apt/lists/*

ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
