name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            name: rpi-infodisplay-aarch64
          - target: armv7-unknown-linux-gnueabihf
            name: rpi-infodisplay-armv7hf
          - target: x86_64-unknown-linux-gnu
            name: rpi-infodisplay-x86_64

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cross
        uses: dtolnay/rust-toolchain@stable

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        run: cross build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          cp target/${{ matrix.target }}/release/rpi-infodisplay ${{ matrix.name }}
          chmod +x ${{ matrix.name }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.name }}
          generate_release_notes: true
